version: '3.0'

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  clean_study_population:
    run: r:latest analysis/1_cohort_cleaning.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/cohort_demo.csv

  # simple_regression:
  #   run: r:latest analysis/3_simple_regression.R
  #   needs: [generate_study_population, clean_study_population]
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/simple_regression.csv

  # describe:
  #   run: r:latest analysis/2_report.R
  #   needs: [generate_study_population]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/descriptive.png
  #       cohort1: output/sex.png


